apiVersion: v1
kind: Service
metadata:
  name: netology-svc
  namespace: netology
spec:
  selector:
    app: netology-web
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 8080
