apiVersion: v1
kind: Service
metadata:
  name: ext-nginx-multitool-service
spec:
  type: NodePort
  selector:
    app: web-debug
  ports:
    - name: nginx
      port: 9001
      targetPort: 80
      nodePort: 30001
    - name: multitool
      port: 9002
      targetPort: 8080
      nodePort: 30002

