apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
  labels:
    app: web-debug
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-debug
  template:
    metadata:
      labels:
        app: web-debug
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
        - name: multitool
          image: wbitt/network-multitool:latest
          ports:
            - containerPort: 8080
          # Запускаем веб-сервер multitool на 8080
          command: ["/bin/sh", "-c", "httpd -p 8080 -h /var/www && echo 'Multitool is running on 8080' > /var/www/index.html && tail -f /dev/null"]

          
